const fs = require('fs');

const bnContent = `const bn = {
  ...en,
  tagline: 'সঠিক দাম। অনুমোদিত রিসাইক্লার। প্রতিটি লটের হিসাব।',
  welcomeHeadline1: 'ই-বর্জ্য আছে?',
  welcomeHeadline2: 'সঠিক জায়গায় বিক্রি করুন।',
  welcomeSub: 'বিক্রির আগে সঠিক দাম জানুন। কাছের অনুমোদিত রিসাইক্লারের কাছে পৌঁছান। প্রতিটি লেনদেনের হিসাব রাখুন।',
  welcomePointPrice: 'আজকের আসল দাম, আপনার ভাষায় শুনুন',
  welcomePointAuthorised: 'শুধুমাত্র অনুমোদিত রিসাইক্লার, আপনার লট অনুযায়ী',
  welcomePointRecord: 'ওজন, দাম এবং পেমেন্টের পাকা রেকর্ড',
  welcomeCta: 'এগিয়ে যান',
  welcomeNote: 'প্রোটোটাইপ · ডেমো ডেটা · সাধারণ ফোন এবং দুর্বল নেটওয়ার্কেও চলে',
  greeting: 'নমস্কার',
  online: 'অনলাইন',
  offline: 'অফলাইন',
  syncing: 'সিঙ্ক হচ্ছে…',
  synced: 'সিঙ্ক হয়েছে',
  demoData: 'ডেমো / প্রোটোটাইপ ডেটা',

  signIn: 'লগ ইন করুন',
  signOut: 'লগ আউট',
  email: 'ইমেইল',
  password: 'পাসওয়ার্ড',
  demoAccounts: 'ডেমো অ্যাকাউন্ট',
  collector: 'সংগ্রাহক',
  recycler: 'রিসাইক্লার',
  admin: 'অ্যাডমিন',
  useAccount: 'এই অ্যাকাউন্ট ব্যবহার করুন',
  wrongLogin: 'ইমেইল বা পাসওয়ার্ড ভুল',
  createAccount: 'নতুন সংগ্রাহক অ্যাকাউন্ট',
  yourName: 'আপনার নাম',
  yourArea: 'আপনার এলাকা',
  register: 'নিবন্ধন করুন',
  backToSignIn: 'লগ ইনে ফিরে যান',

  sellEwaste: 'ই-বর্জ্য বিক্রি করুন',
  todaysPrices: 'আজকের দাম',
  findRecycler: 'রিসাইক্লার খুঁজুন',
  myEarnings: 'আমার উপার্জন',
  myLots: 'আমার লট',
  safety: 'নিরাপত্তা',
  installApp: 'অ্যাপ ইনস্টল করুন',
  todaysBoard: 'আজকের দামের তালিকা',

  newLot: 'নতুন লট',
  step: 'ধাপ',
  photo: 'ছবি',
  takePhoto: 'ছবি তুলুন',
  uploadPhoto: 'গ্যালারি থেকে বেছে নিন',
  retake: 'আবার তুলুন',
  aiChecking: 'ছবি চেক করা হচ্ছে…',
  likelyMaterial: 'সম্ভাব্য জিনিস',
  confidence: 'নিশ্চয়তা',
  correct: 'সঠিক',
  change: 'পরিবর্তন করুন',
  chooseMaterial: 'জিনিস বেছে নিন',
  weight: 'ওজন',
  weightKg: 'ওজন কেজিতে',
  condition: 'অবস্থা',
  good: 'ভালো',
  damaged: 'খারাপ',
  mixed: 'মিশ্র',
  source: 'কোথা থেকে',
  household: 'বাড়ি থেকে',
  commercial: 'দোকান/অফিস',
  industrial: 'কারখানা',
  scrap_collection: 'ফেরি থেকে',
  next: 'পরবর্তী',
  back: 'পেছনে',
  saveDraft: 'পরে সেভ করার জন্য রাখুন',
  draftSaved: 'ফোনে সেভ হয়েছে। নেট আসলে আপলোড হবে।',

  estimatedValue: 'আনুমানিক মূল্য',
  marketRate: 'আজকের বাজার দর',
  trend: 'ট্রেন্ড',
  rising: 'বাড়ছে',
  falling: 'কমছে',
  stable: 'স্থিতিশীল',
  perKg: 'প্রতি কেজি',
  estimateNote:
    'এটি আনুমানিক বাজার দর, চূড়ান্ত দাম নয়। আসল দাম ওজনের পর রিসাইক্লারের সাথে ঠিক হবে।',
  priceHistory: 'গত ৪৫ দিনের দাম',
  selectMaterialForChart: 'দাম দেখতে জিনিসে ট্যাপ করুন',

  bestMatch: 'সবচেয়ে ভালো মিল',
  otherOptions: 'অন্যান্য অনুমোদিত রিসাইক্লার',
  match: 'মিল',
  kmAway: 'কিমি দূরে',
  pickupAvailable: 'পিকআপ উপলব্ধ',
  noPickup: 'নিজেকে পৌঁছে দিতে হবে',
  authorised: 'অনুমোদিত',
  chooseThis: 'এই রিসাইক্লার বেছে নিন',
  offerFor: 'আপনার লটের জন্য',
  whyThisScore: 'এই স্কোর কীভাবে তৈরি হয়',
  onlyAuthorised: 'শুধুমাত্র অনুমোদিত রিসাইক্লার দেখানো হয়।',
  earnMore: 'আপনি আরও আয় করতে পারেন',
  informalOffer: 'সাধারণ কবরি দাম',
  formalOffer: 'এই রিসাইক্লার দেবে',
  extraValue: 'অতিরিক্ত সুবিধা',
  noMatches: 'এই জিনিসের জন্য কাছে কোনও অনুমোদিত রিসাইক্লার নেই।',

  lotId: 'লট নম্বর',
  showQr: 'রিসাইক্লারকে এই QR দেখান',
  qrNote: 'QR-এ শুধু লট নম্বর থাকে। বাকি তথ্য রিসাইক্লারের অ্যাপ সার্ভার থেকে নেয়।',
  status: 'অবস্থা',
  timeline: 'অগ্রগতি',
  handoverRef: 'হস্তান্তর নম্বর',
  quotedPrice: 'নির্ধারিত দাম',
  finalPrice: 'চূড়ান্ত দাম',
  finalWeight: 'চূড়ান্ত ওজন',
  paymentMode: 'পেমেন্টের উপায়',
  cash: 'নগদ',
  upi: 'ইউপিআই',
  paid: 'পাওয়া গেছে',
  pending: 'বাকি',
  viewLot: 'লট দেখুন',

  totalEarnings: 'মোট উপার্জন',
  thisMonth: 'এই মাসে',
  pendingAmount: 'বাকি',
  transactions: 'লেনদেন',
  noTransactions: 'এখনও কোনো লেনদেন নেই। প্রথম লট তৈরি করুন।',
  kgSold: 'কেজি বিক্রি হয়েছে',

  safetyTitle: 'নিরাপদে কাজ করুন',
  safetyIntro: 'ভাঙ্গারির কাজে আঘাতের চারটি প্রধান কারণ।',
  safeCables: 'তার কখনও পোড়াবেন না',
  safeCablesBody: 'তার পোড়ালে বিষাক্ত ধোঁয়া বের হয়। হাতিয়ার দিয়ে ছিলুন।',
  safeBattery: 'ব্যাটারি ভাঙবেন ফেব্রুয়ারি বা ফুটো করবেন না',
  safeBatteryBody: 'ফুটো করা ব্যাটারি কয়েক সেকেন্ডে আগুন ধরে যেতে পারে। শুকনো বাক্সে রাখুন।',
  safeAcid: 'ধাতু বের করতে অ্যাসিড ব্যবহার করবেন না',
  safeAcidBody: 'অ্যাসিড চামড়া এবং ফুসফুস পোড়ায় এবং জিনিসের দামও কমায়।',
  safeCrt: 'সিআরটি টিউব আস্ত রাখুন',
  safeCrtBody: 'পিকচার টিউবে সীসাযুক্ত কাঁচ ভ্যাকুয়ামে থাকে। কখনও ভাঙবেন না।',
  listen: 'শুনুন',
  gpsOn: 'লোকেশন যুক্ত করা হয়েছে',
  gpsAsking: 'লোকেশন নেওয়া হচ্ছে…',
  gpsOff: 'লোকেশন যুক্ত করা হয়নি',
  gpsEnable: 'আমার লোকেশন ব্যবহার করুন',
  accept: 'গ্রহণ করুন',
  reject: 'প্রত্যাখ্যান করুন',
  nearbyRecyclers: 'আপনার কাছের অনুমোদিত রিসাইক্লার',
  overview: 'প্ল্যাটফর্ম ওভারভিউ',
  registeredCollectors: 'নিবন্ধিত সংগ্রাহক',
  authorisedRecyclers: 'অনুমোদিত রিসাইক্লার',
  totalLots: 'মোট লট',
  ewasteCollected: 'সংগৃহীত ই-বর্জ্য',
  formalTransactions: 'আনুষ্ঠানিক লেনদেন',
  totalValue: 'মোট মূল্য',
  verification: 'যাচাইকরণ',
  traceability: 'ট্রেসেবিলিটি',
  anomalies: 'অসঙ্গতি',
  priceData: 'দামের ডেটা',
  map: 'মানচিত্র',
  approve: 'মঞ্জুর করুন',
  documents: 'নথিপত্র',
  view: 'দেখুন',
  searchLotId: 'লট নম্বর খুঁজুন',
  search: 'খুঁজুন',
  materialMix: 'উপাদান বিতরণ (কেজি)',
  monthlyCollection: 'মাসিক সংগ্রহ',
  paymentStatus: 'পেমেন্ট অবস্থা',
  priceTrends: 'দামের প্রবণতা',
  anomalyNone: 'কোনও অসঙ্গতি নেই।',
  collectionPoints: 'সংগ্রহ কেন্দ্র এবং সুবিধা',
  dashboard: 'ড্যাশবোর্ড',
  pendingTransactions: 'বাকি লেনদেন',
  allRecyclers: 'সমস্ত রিসাইক্লার',
  pendingLabel: 'বাকি',
  authorisationId: 'অনুমোদন নম্বর',
  materialsLabel: 'উপাদান',
  contactLabel: 'যোগাযোগ',
  nameLabel: 'নাম',
  locationLabel: 'স্থান',
  statusLabel: 'অবস্থা',
  pickupLabel: 'পিকআপ',
  actionsLabel: 'কাজ',
  materialLabel: 'জিনিস',
  declaredWeightLabel: 'ঘোষিত ওজন',
  finalWeightLabel: 'চূড়ান্ত ওজন',
  finalPriceLabel: 'চূড়ান্ত দাম',
  quotedLabel: 'নির্ধারিত দাম',
  facilityLabel: 'সুবিধা',
  authorisationLabel: 'অনুমোদন',
  matchScoreLabel: 'মিলের স্কোর',
  areaLabel: 'এলাকা',
  createdLabel: 'তৈরি হয়েছে',
  conditionLabel: 'অবস্থা',
  sourceLabel: 'উৎস',
  estimateLabel: 'অনুমান',
  aiSuggestionLabel: 'এআই পরামর্শ',
  handoverPaymentLabel: 'হস্তান্তর এবং পেমেন্ট',
  verifiedAtLabel: 'যাচাই করার সময়',
  gpsLabel: 'জিপিএস',
  handoverPointLabel: 'হস্তান্তর স্থান',
  paymentLabel: 'পেমেন্ট',
  paymentStatusLabel: 'পেমেন্টের অবস্থা',
  collectionPointLabel: 'সংগ্রহ কেন্দ্র',
  amountLabel: 'পরিমাণ',
  updatedLabel: 'আপডেট হয়েছে',
  dateLabel: 'তারিখ',
  weightLabel: 'ওজন',
  rateLabel: 'দাম',
  sourceDataLabel: 'উৎস',
  anomalyNoneShort: 'কোনও অসঙ্গতি নেই।',
  anomalyIntro: 'যখন প্রতি কেজির দাম গত ৯০ দিনের তুলনায় অস্বাভাবিক হয় এবং গড়ের চেয়ে ১৫% এর বেশি আলাদা হয়, অথবা চূড়ান্ত ওজন ঘোষিত ওজনের চেয়ে ২৫% এর বেশি আলাদা হয় তখন চিহ্নিত করা হয়।',
  verificationIntro: 'শুধুমাত্র অনুমোদিত রিসাইক্লারদের সংগ্রাহকদের কাছে সুপারিশ করা হয়। এগুলি ডেমো কোম্পানি — এখানে অনুমোদন একটি প্রোটোটাইপ প্রক্রিয়া, সরকারি অনুমোদন নয়।',
  priceDataIntro: 'নতুন দামের রেকর্ড। যেগুলির উৎস recycler_update সেগুলি এই সেশনেই রিসাইক্লার দ্বারা পরিবর্তন করা হয়েছে।',
  traceIntro: 'প্রতিটি লট একটি শৃঙ্খল: সংগ্রাহক → লট → দাম → রিসাইক্লার → হস্তান্তর → পেমেন্ট।',
  noLotsWaiting: 'কোনও লট বাকি নেই।',
  figuresNote: 'সমস্ত পরিসংখ্যান প্রোটোটাইপ ডেটা থেকে আসে এবং ডেমোর সাথে আপডেট হয়।',
  language: 'ভাষা',
  profileSaved: 'নাম পরিবর্তন হয়েছে',
  backendConnected: 'সার্ভার যুক্ত আছে',
  backendDisconnected: 'সার্ভার যুক্ত নেই',
  backendDown: 'সার্ভারের সাথে যোগাযোগ করা যাচ্ছে না। পরিবর্তনগুলি এখন সেভ হবে বিন্দু।',
  demoModeOn: 'ডেমো মোড',
  retry: 'আবার চেষ্টা করুন',
  loadFailed: 'সার্ভার থেকে তথ্য পাওয়া যায়নি।',
  capture: 'ছবি তুলুন',
  switchCamera: 'ক্যামেরা পরিবর্তন করুন',
  cameraStarting: 'ক্যামেরা চালু হচ্ছে…',
  cameraDenied: 'ব্রাউজার এই সাইটের জন্য ক্যামেরা ব্লক করেছে। অ্যাড্রেস বারে ক্যামেরা/লক আইকনে ক্লিক করে অনুমতি দিন, তারপর “আবার চেষ্টা করুন” এ ক্লিক করুন। অথবা গ্যালারি থেকে ছবি বেছে নিন।',
  cameraRetry: 'ক্যামেরা আবার চেষ্টা করুন',
  outOfServiceArea: 'আপনার এলাকায় এই জিনিসের জন্য কোনও রিসাইক্লার আসে না। এগুলি সবচেয়ে কাছের অনুমোদিত রিসাইক্লার — আপনাকে পরিবহন করতে হবে।',
  sameCity: 'এই শহরেই',
  usePhoto: 'এই ছবি ব্যবহার করুন',
  retakePhoto: 'আবার তুলুন',
  photoPreview: 'ছবি দেখে নিন',
  noPhotoReturned: 'কোনও ছবি পাওয়া যায়নি। আবার চেষ্টা করুন বা গ্যালারি থেকে বেছে নিন।',
  verdictEwaste: 'ই-বর্জ্য পাওয়া গেছে',
  verdictNot: 'ই-বর্জ্য নয়',
  verdictUncertain: 'নিশ্চিত নয়',
  checkedBy: 'যাচাই করেছে',
  accountType: 'অ্যাকাউন্টের ধরন',
  createCollectorAccount: 'নতুন সংগ্রাহক অ্যাকাউন্ট',
  createRecyclerAccount: 'নতুন রিসাইক্লার অ্যাকাউন্ট',
  adminNoSignup: 'অ্যাডমিন অ্যাকাউন্ট প্ল্যাটফর্ম অপারেটর তৈরি করে।',
  roleMismatch: 'বেছে নেওয়া অ্যাকাউন্টের ধরন এই লগইনের সাথে মিলছে না। আপনি {selected} বেছে নিয়েছেন, এটি একটি {actual} অ্যাকাউন্ট।',
  ratesUnavailable: 'দামের তালিকা লোড করা যায়নি',
  ratesEmpty: 'এখনও কোনও দাম উপলব্ধ নেই',
  ratesEmptyHint: 'সার্ভারে দামের ডেটা নেই।',
  demoDataNote: 'প্রোটোটাইপ · ডেমো ডেটা',
  nonEwaste: 'এটি ই-বর্জ্য নয়',
  uploadAgain: 'অন্য ছবি আপলোড করুন',
  micLangUnsupported: 'এই ফোনে {lang}-এর জন্য ভয়েস রিকগনিশন নেই। হিন্দিতে চেষ্টা করুন বা বোতাম ব্যবহার করুন।',
  micTryHindi: 'হিন্দিতে চেষ্টা করুন',
  micUseButtons: 'বোতাম ব্যবহার করুন',
  micNoDevice: 'এই ফোনে কোনও মাইক্রোফোন পাওয়া যায়নি।',
  voiceSell: 'বলে বিক্রি করুন',
  voiceHint: 'ওজন এবং জিনিস বলুন। যেমন: "সাড়ে আট কেজি তার"।',
  voiceStart: 'চেপে ধরে বলুন',
  voiceStop: 'থামান',
  voiceListening: 'শুনছি…',
  voiceAgain: 'আবার বলুন',
  voiceOrTap: 'বা নিচের বোতাম চাপুন',
  micDenied: 'মাইক্রোফোনের অনুমতি প্রয়োজন। অনুমতি দিন, বা নিচের বোতাম ব্যবহার করুন।',
  micNoSpeech: 'কিছু শোনা যায়নি। আবার বলুন বা নিচের বোতাম ব্যবহার করুন।',
  micNetwork: 'ভয়েস ইনপুটের জন্য ইন্টারনেট প্রয়োজন। নিচের বোতাম ব্যবহার করুন।',
  micUnsupported: 'এই ব্রাউজারে ভয়েস ইনপুট কাজ করবে না। নিচের বোতাম ব্যবহার করুন।',
  micNoMaterial: 'জিনিস পরিষ্কার বোঝা যায়নি। আবার বলুন বা নিচে বেছে নিন।',
  micNoWeight: 'ওজন পরিষ্কার বোঝা যায়নি। আবার বলুন বা নিচে পূরণ করুন।',
  fairnessWeight: 'ওজনে পার্থক্য আছে — ওজন পরীক্ষা করুন',
  fairnessPrice: 'দাম বাজার দরের চেয়ে কম',
  declaredWeight: 'আপনি বলেছেন',
  recordedWeight: 'রেকর্ড করা হচ্ছে',
  scalePhoto: 'ওজন মাপার মেশিনের ছবি',
  scalePhotoHint: 'মেশিনের একটি ছবি তুলুন যাতে চূড়ান্ত ওজন দেখা যায়। এটি রেকর্ডে রাখা হবে।',
  scalePhotoRequired: 'হস্তান্তরের আগে ওজন মাপার মেশিনের ছবি প্রয়োজন।',
  estimator: 'মূল্য অনুমান',
  estimatorTitle: 'আপনার ভাঙ্গারির মূল্য অনুমান করুন',
  estimatorIntro: 'জয়পুরের প্রকাশিত দর, আপনার এলাকা, অবস্থা এবং পরিমাণ অনুযায়ী।',
  estimatorPickItem: 'জিনিস বেছে নিন (সবচেয়ে বেশি দাম আগে)',
  estimatorQuantity: 'পরিমাণ',
  estimatorLocality: 'এলাকা',
  estimatorQuality: 'অবস্থা',
  estimatorGo: 'মূল্য অনুমান করুন',
  estimatorResult: 'আপনার ভাঙ্গারির অনুমান',
  estimatorPublished: 'প্রকাশিত দর',
  estimatorAdjusted: 'আনুমানিক দর',
  estimatorNoPay: 'কেনা হয় না',
  estimatorSource: 'ডেটা উৎস',
  quality_clean: 'পরিষ্কার / বাছাই করা',
  quality_mixed: 'মিশ্র',
  quality_dirty: 'নোংরা',
  quality_damaged: 'ভাঙা',
  offers: 'অফার',
  openLots: 'খোলা লট',
  makeOffer: 'অফার দিন',
  reviseOffer: 'অফার পরিবর্তন করুন',
  yourOffer: 'আপনার অফার',
  offerSent: 'অফার সংগ্রাহকের কাছে পাঠানো হয়েছে',
  ratePerKg: 'দাম প্রতি কেজি',
  offerNote: 'নোট (ঐচ্ছিক)',
  offerPickup: 'আমি এসে নিয়ে যেতে পারি',
  acceptOffer: 'গ্রহণ করুন',
  offersReceived: 'প্রাপ্ত অফার',
  noOffersYet: 'এখনও কোনও অফার নেই। রিসাইক্লাররা এই লটটি দেখতে পারেন এবং অফার পাঠাবেন।',
  offerAccepted: 'অফার গৃহীত হয়েছে',
  waitingForOffers: 'অফারের অপেক্ষায়',
  otherMaterial: 'অন্যান্য',
  noPublishedRate: 'এই জিনিসের কোনও নির্দিষ্ট দাম নেই — রিসাইক্লার ওজনের পর দাম জানাবে।',
  cameraNone: 'এই ফোনে কোনও ক্যামেরা নেই। ছবি আপলোড করুন।',
  cameraUnsupported: 'এখানে লাইভ ক্যামেরা কাজ করবে না। ছবি আপলোড করুন।',
  cameraInsecure: 'লাইভ ক্যামেরার জন্য সুরক্ষিত (https) পেজ প্রয়োজন। ছবি আপলোড করুন।',
  notEwaste: 'এটি ই-বর্জ্য বলে মনে হচ্ছে না',
  tryAgain: 'আরেকটি ছবি তুলুন',
  chooseAnyway: 'আমি নিজেই জিনিসটি বেছে নেব',
  lowConfidence: 'এই ছবি সম্পর্কে নিশ্চিত নই',

  incomingLots: 'আসা লট',
  scanLotQr: 'লট QR স্ক্যান করুন',
  buyingRates: 'কেনার দাম',
  profile: 'প্রোফাইল',
  activeLots: 'চলতি লট',
  todaysCollection: 'আজকের সংগ্রহ',
  pendingHandover: 'হস্তান্তর বাকি',
  completed: 'সম্পন্ন',
  verifyLot: 'লট যাচাই করুন',
  confirmHandover: 'হস্তান্তর নিশ্চিত করুন',
  markPaid: 'পেমেন্ট মার্ক করুন',
  enterFinalWeight: 'চূড়ান্ত ওজন (কেজি)',
  enterFinalPrice: 'চূড়ান্ত দাম (₹)',
  acceptedMaterials: 'গৃহীত উপাদান',
  serviceArea: 'পরিষেবা এলাকা (কিমি)',
  saveChanges: 'সেভ করুন',
  ratesSaved: 'দাম পরিবর্তন হয়েছে। সংগ্রাহকরা নতুন দাম সাথে সাথে দেখতে পাবেন।',
  scanHelp: 'ক্যামেরা সংগ্রাহকের লট QR এর দিকে ধরুন।',
  enterLotManually: 'বা লট নম্বর টাইপ করুন',
  open: 'খুলুন',
  cameraBlocked: 'এখানে ক্যামেরা উপলব্ধ নয় — লট নম্বর টাইপ করুন।',
  notFound: 'এই নম্বরের কোনও লট পাওয়া যায়নি।',
};`;

let content = fs.readFileSync('src/i18n/index.jsx', 'utf8');

// Use string split and replace
const startIndex = content.indexOf('const mr = {');
const endIndex = content.indexOf('};', startIndex) + 2;

if (startIndex !== -1 && endIndex !== -1) {
  content = content.substring(0, startIndex) + bnContent + content.substring(endIndex);
  fs.writeFileSync('src/i18n/index.jsx', content);
  console.log('Successfully replaced mr with bn');
} else {
  console.log('Could not find const mr block');
}
